application:
  debug: true
ibm:
  iib:
    node: TSTIPD01
    connName: localhost(4415)
    user1: 
    password1:
    useSSL1: false 
    event:
      delayInMilliSeconds: 10000
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
info:
  app:
    name: IIB-Metrics
    description: IBM IIB Monitoring Metrics (Dev)
    version: 1.0.0.0
    java:
      version: 1.8.0.0
server:
  port:
    8083
