application:
  debug: false
ibm:
  iib:
    node: TSTIPD01
    connName: localhost(4415)
    user: mqmon01 
    password: ENC(7t/0rMBZBJcd4xkg7wufOWNRtyEVOg+3)
    useSSL: false 
    event:
      delayInMilliSeconds: 10000
jasypt:
  encryptor:
    password: secretkey      
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
info:
  app:
    name: IIB-Metrics
    description: IBM IIB Monitoring Metrics (Dev)
    version: 1.0.0.3
    java:
      version: 1.8.0.0
server:
  port:
    8083
